# Create Auth Secret
apiVersion: v1
kind: Secret
metadata:
  name: auth-secrets
type: Opaque
data:
  DB_HOST: {{ .Values.global.database.host | toString | b64enc }}
  DB_PORT: {{ .Values.global.database.port | toString | b64enc }}
  DB_PASSWORD: {{ .Values.global.secrets.authDbPassword | toString | b64enc }}
  JWT_SECRET: {{ .Values.global.secrets.jwtSecret | toString | b64enc }}
---
# Create Order Secret
apiVersion: v1
kind: Secret
metadata:
  name: order-secrets
type: Opaque
data:
  DB_HOST: {{ .Values.global.database.host | toString | b64enc }}
  DB_PORT: {{ .Values.global.database.port | toString | b64enc }}
  DB_PASSWORD: {{ .Values.global.secrets.orderDbPassword | toString | b64enc }}