apiVersion: v1
kind: ConfigMap
metadata:
  name: shared-global-config
  labels:
    app.kubernetes.io/name: ecommerce-app
data:
  NODE_ENV: {{ .Values.global.env | quote }}
  AWS_REGION: {{ .Values.global.awsRegion | quote }}
  DB_HOST: {{ .Values.global.database.host | quote }}
  DB_PORT: {{ .Values.global.database.port | quote }}
  LOG_LEVEL: {{ .Values.global.sharedEnv.LOG_LEVEL | quote }}
  AUTH_API_URL: {{ .Values.global.sharedEnv.AUTH_API_URL | quote }}
  ORDER_API_URL: {{ .Values.global.sharedEnv.ORDER_API_URL | quote }}
  PAYMENT_API_URL: {{ .Values.global.sharedEnv.PAYMENT_API_URL | quote }}
  CART_API_URL: {{ .Values.global.sharedEnv.CART_API_URL | quote }}
  PRODUCT_API_URL: {{ .Values.global.sharedEnv.PRODUCT_API_URL | quote }}
  NOTIFICATION_API_URL: {{ .Values.global.sharedEnv.NOTIFICATION_API_URL | quote }}