apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/part-of: ecommerce-app
data:
  SERVICE_NAME: {{ .Chart.Name | quote }}
  PORT: {{ .Values.service.port | quote }}
  HELM_RELEASE_NAME: {{ .Release.Name | quote }}
  HELM_RELEASE_NAMESPACE: {{ .Release.Namespace | quote }}
  
