apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
  labels:
    app: {{ .Chart.Name }}
data:
  # Environment Discovery
  NODE_ENV: {{ .Values.env | default "production" | quote }}
  REGION: {{ .Values.awsRegion | default "us-east-1" | quote }}

  DB_HOST: {{ .Values.databaseHost | quote }}
  DB_PORT: {{ .Values.databasePort | quote }}

  # Internal Service Discovery
  AUTH_API_URL: "http://auth:8080"
  CART_API_URL: "http://cart:8081"
  NOTIFICATION_API_URL: "http://notification:8082"
  ORDER_API_URL: "http://order:8083"
  PAYMENT_API_URL: "http://payment:8084"
  PRODUCT_API_URL: "http://product:8085"

  # App Specific
  PORT: {{ .Values.service.port | quote }}
  LOG_LEVEL: "info"