apiVersion: v1
kind: Secret
metadata:
  # Named after the service to keep it organized
  name: {{ .Chart.Name }}-secrets
  labels:
    app: {{ .Chart.Name }}
type: Opaque
data:
  # The | b64enc function is built-in to Helm. 
  # It automatically converts your plain text into the Base64 format K8s requires.
  DB_PASSWORD: {{ .Values.secrets.dbPassword | b64enc | quote }}
  JWT_SECRET: {{ .Values.secrets.jwtSecret | b64enc | quote }}



  