replicaCount: 1

image:
  registry: ""
  repository: product-service
  tag: latest

service:
  type: ClusterIP
  port: 8085

externalApi: "https://dummyjson.com"

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "256Mi"
