replicaCount: 1

image:
  repository: "auth-service"

service:
  type: ClusterIP
  port: 8080

database:
  name: "auth_db"

secrets:
  dbPassword: "" 
  jwtSecret: ""

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "256Mi"