events { 
    worker_connections 1024; 
}

http {
    # Docker's internal DNS resolver
    resolver 127.0.0.11 valid=30s;

    server {
        listen 80;

        # 1. GATEWAY HEALTH (Root)
        location / {
            return 200 '{"status": "Gateway is Up", "project": "EKS-Microservices"}';
            add_header Content-Type application/json;
        }

        # 2. AUTH SERVICE
        location /auth/ {
            set $auth_upstream http://auth:3000;
            proxy_pass $auth_upstream/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # 3. PRODUCT SERVICE
        location /product/ {
            set $product_upstream http://product:3000;
            proxy_pass $product_upstream/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # 4. CART SERVICE
        location /cart/ {
            set $cart_upstream http://cart:3000;
            proxy_pass $cart_upstream/;
        }

        # 5. ORDER SERVICE
        location /order/ {
            set $order_upstream http://order:3000;
            proxy_pass $order_upstream/;
        }

        # 6. PAYMENT SERVICE
        location /payment/ {
            set $payment_upstream http://payment:3000;
            proxy_pass $payment_upstream/;
        }

        # 7. NOTIFICATION SERVICE
        location /notification/ {
            set $notif_upstream http://notification:3000;
            proxy_pass $notif_upstream/;
        }
    }
}