apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-global-secrets
  labels:
    app: ecommerce-platform
type: Opaque
data:
  # These lines tell Helm: "Go to the root values.yaml, find the 
  # secret, encode it to Base64, and put it here."
  AUTH_DB_PASSWORD: {{ .Values.global.secrets.authDbPassword | b64enc | quote }}
  ORDER_DB_PASSWORD: {{ .Values.global.secrets.orderDbPassword | b64enc | quote }}
  JWT_SECRET_KEY: {{ .Values.global.secrets.jwtSecret | b64enc | quote }}
  STRIPE_API_KEY: {{ .Values.global.secrets.stripeApiKey | b64enc | quote }}