env: "production"
awsRegion: "us-east-1"
replicaCount: 1

image:
  registry: ""
  repository: order-service
  tag: latest

service:
  type: ClusterIP
  port: 8083

database:
  host: "postgres.default.svc.cluster.local"
  port: 5432

secrets:
  create: true
  dbUser: "postgres"
  dbPassword: "postgres"
  dbName: "order_db"

resources: {}
