replicaCount: 1

image:
  repository: orders-service
  tag: latest

service:
  type: ClusterIP
  port: 8083

secrets:
  dbPassword: ""
  dbName: "order_db"

resources:
  requests:
    cpu: "10m"       # Only request 1% of a core
    memory: "32Mi"   # Very small start-up memory
  limits:
    cpu: "100m"
    memory: "128Mi"
