apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
  labels:
    app: {{ .Chart.Name }}
data:
  NODE_ENV: {{ .Values.env | default .Values.global.env | quote }}
  REGION: {{ .Values.awsRegion | default .Values.global.awsRegion | quote }}
  PORT: {{ .Values.service.port | quote }}
