replicaCount: 1

image:
  registry: ""
  repository: frontend-service
  tag: latest

service:
  type: ClusterIP
  port: 80

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "256Mi"
