apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          # Fallback logic: Use sub-chart registry or global AWS ECR
          image: "{{ .Values.global.repository }}/{{ .Chart.Name }}:{{ .Values.global.tag | default "latest" }}"
          ports:
            - containerPort: {{ .Values.service.port }}
          
          envFrom:
            # Service-specific settings (e.g., DB Name)
            - configMapRef:
                name: {{ .Chart.Name }}-config
            # Global settings (e.g., DB Host/RDS Endpoint)
            - configMapRef:
                name: shared-global-config
            # The Global Secret (Passwords and Keys)
            - secretRef:
                name: ecommerce-global-secrets

          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu}}
              memory: {{ .Values.resources.requests.memory}}
            limits:
              cpu: {{ .Values.resources.limits.cpu}}
              memory: {{ .Values.resources.limits.memory}}