apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.registry | default .Values.global.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Values.global.tag }}"
          ports:
            - containerPort: {{ .Values.service.port }}
          
          # Loading non-sensitive data from both service-specific and global ConfigMaps
          envFrom:
            - configMapRef:
                name: {{ .Chart.Name }}-config
            - configMapRef:
                name: shared-global-config
          
          # Pulling the specific Order DB password from the root secrets file
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ecommerce-global-secrets
                  key: ORDER_DB_PASSWORD

          resources:
            {{- toYaml .Values.resources | nindent 12 }}