apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          # Fallback logic: Use sub-chart registry or global AWS ECR
          image: "{{ .Values.global.repository }}/{{ .Values.image.repository }}:{{ .Values.global.tag | default .Values.image.tag | default "latest" }}"
          ports:
            - containerPort: {{ .Values.service.port }}
          
         # templates/deployment.yaml (for order service)
          envFrom:
            - configMapRef:
                name: {{ .Chart.Name }}-config
            - configMapRef:
                name: shared-global-config
            - secretRef: 
                name: order-secrets # Only Auth/Order get the Password # Helm renders this as {{ .Chart.Name }}-secrets

          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}