apiVersion: v2
name: ecommerce-app
description: A root helm chart for the 7-service ecommerce application
type: application

version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: auth
    version: 0.1.0
    repository: "file://charts/auth"
  - name: frontend
    version: 0.1.0
    repository: "file://charts/frontend"
  - name: cart
    version: 0.1.0
    repository: "file://charts/cart"
  - name: product
    version: 0.1.0
    repository: "file://charts/product"
  - name: payment
    version: 0.1.0
    repository: "file://charts/payment"
  - name: order
    version: 0.1.0
    repository: "file://charts/order"
  - name: notification
    version: 0.1.0
    repository: "file://charts/notification"
