# root secrets.yaml
global:
  secrets:
    authDbPassword: "Abdurahman123$$"
    orderDbPassword: "Abdurahman123$$"
    jwtSecret: "ecom-v1-super-secret-key-2026-auth"
    stripeApiKey: "sk_test_51MzE2aL7p8q9r0s1t2u3v4w5x6y7z"