# --- GLOBAL SETTINGS ---
global:
  registry: 123456789.dkr.ecr.us-east-1.amazonaws.com
  tag: "latest"
  awsRegion: "us-east-1"
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

# --- EXTERNAL SECRETS CONFIG ---
# This section is required for your ClusterSecretStore template
eso:
  namespace: "external-secrets"
  serviceAccountName: "external-secrets"
aws:
  region: "us-east-1"

# --- INDEPENDENT SERVICE OVERRIDES ---
frontend:
  replicaCount: 1
  image:
    repository: "ecommerce-frontend"
  service:
    port: 80
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

auth:
  replicaCount: 1
  image:
    repository: "ecommerce-auth"
  service:
    type: ClusterIP
    port: 8080
  # --- ADDED FOR ESO ---
  secrets:
    rdsSecretArn: "arn:aws:secretsmanager:us-east-1:123456789:secret:baashe-db-xyz"
    jwtSecret: "a-long-random-32-character-string"

cart:
  replicaCount: 1
  image:
    repository: "ecommerce-cart"
  service:
    port: 8081
  # --- ADDED FOR ESO ---
  secrets:
    rdsSecretArn: "arn:aws:secretsmanager:us-east-1:123456789:secret:baashe-db-xyz"

notification:
  replicaCount: 1
  image:
    repository: "ecommerce-notification"
  service:
    port: 8082

order:
  replicaCount: 1
  image:
    repository: "ecommerce-order"
  service:
    port: 8083
  # --- ADDED FOR ESO ---
  secrets:
    rdsSecretArn: "arn:aws:secretsmanager:us-east-1:123456789:secret:baashe-db-xyz"

payment:
  replicaCount: 1
  image:
    repository: "ecommerce-payment"
  service:
    port: 8084
  resources:
    requests:
      cpu: 250m
      memory: 256Mi

product:
  replicaCount: 1
  image:
    repository: "ecommerce-product"
  service:
    port: 8085